export const AUTHORISE = 'AUTHORISE';
export const FETCH_BENCHMARKS = 'FETCH_BENCHMARKS';
export const FETCH_COMMITS = 'FETCH_COMMITS';
export const FETCH_INSTALLATIONS = 'FETCH_INSTALLATIONS';
export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES';
